[package]
name = "minecraft_map_tool"
authors = ["Ossi Saukko <osaukko@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
comfy-table = "6.1.3"
crossterm = "0.25.0"
fastnbt = "2.3.2"
flate2 = "1.0.24"
image = "0.24.5"
natord = "1.0.9"
serde_json = "1.0.89"

[dependencies.phf]
features = ["macros"]
version = "0.11.1"

[dependencies.clap]
features = ["derive"]
version = "4.0.29"

[dependencies.serde]
features = ["derive"]
version = "1.0.148"