[package]
name = "minecraft_map_tool"
authors = ["Ossi Saukko <osaukko@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { features = ["derive"], version = "4.0.29" }
comfy-table = "6.1.3"
crossterm = "0.25.0"
flate2 = "1.0.24"
image = "0.24.5"
natord = "1.0.9"
valence_nbt = "0.4.0"
