[package]
name = "minecraft_map_tool"
authors = ["Ossi Saukko <osaukko@gmail.com>"]
description = "Utility for handling Minecraft map files"
version = "0.2.0"
edition = "2021"

[dependencies]
comfy-table = "6"
crossterm = "0"
fastnbt = "2"
flate2 = "1"
image = "0"
natord = "1"
serde_json = "1"

[dependencies.clap]
features = ["derive"]
version = "4"

[dependencies.phf]
features = ["macros"]
version = "0"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.viuer]
features = ["sixel"]
version = "0"

[dev-dependencies]
hex = "0"

[features]
# Builds a test subcommand that can be used to create files for testing
test_tool = []
